name: Scan for Secrets

on:
  push:
    branches: [ $default-branch ]
  pull_request:

# GitHub Action workflow has permissions to write comments and update pull requests
permissions:
  contents: read
  id-token: write
  issues: write
  pull-requests: write

jobs:
  TruffleHog:
    runs-on: ubuntu
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: TruffleHog OSS
        id: trufflehog
        uses: trufflesecurity/trufflehog@main
        continue-on-error: true 
        with:
          extra_args: --debug --only-verified

# Finally, we’ll make sure that if a secret is detected, the run fails:
      - name: Scan Results Status
        if: steps.trufflehog.outcome == 'failure'
        run: exit 1
